### ISSUE TITLE
App strings in Arabic

### ISSUE THREAD

**Issue by comradekingu** [prateekmedia/pstube#23] opened 2022-01-31 07:00 UTC
Downloaded 1.1.0 from IzzyOnDroid
Default locale nb_NO;nn_NO;da;se

Don't know how to turn it off ;)

**Comment by prateekmedia** [comment] 2022-01-31 17:42
You downloaded this app from IzzyOnDroid? I haven't published it there.

**Comment by wdkevonfernando** [comment] 2022-04-03 18:23
I have the same issue on Linux with version 2.0.0. It would be nice to keep this issue open until a workaround or fix has been implemented. In doing so, users who come here will not be confused.

**Comment by dCo3lh0** [comment] 2022-04-25 01:34
i have the same problem, with your appimage pool last version and pstube too. Both shows in arabic, so i use the version before the latest

**Comment by prateekmedia** [comment] 2022-04-25 01:53
Anyone facing this can try the new nightly version

**Comment by Raitsa** [comment] 2022-04-25 19:46
Nightly fixed android version ok 👍

**Closed** 2023-01-05 09:47 UTC

**Comment by ju1ius** [comment] 2023-04-24 06:46
FYI, the issue is present on the latest stable flatpak release from flathub.
